# Generated by Django 2.2.1 on 2019-08-15 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Group ID')),
                ('name', models.CharField(max_length=100, verbose_name='Group Name')),
                ('description', models.TextField(max_length=250, verbose_name='Group Description')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='School Name')),
                ('address', models.TextField(blank=True, max_length=250, null=True, verbose_name='School Address')),
                ('country', models.CharField(choices=[('AE', 'UAE'), ('US', 'USA'), ('JP', 'Japan'), ('ID', 'Indonesia')], default='AE', max_length=100, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Section Name')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Group', verbose_name='Group')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.School', verbose_name='School')),
            ],
        ),
    ]
