# Generated by Django 2.2.1 on 2019-08-17 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(max_length=5, primary_key=True, serialize=False, verbose_name='Group ID')),
                ('name', models.CharField(max_length=100, verbose_name='Group Name')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Group Description')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('Sun', 'Sunday'), ('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fri', 'Friday'), ('Sat', 'Saturday')], max_length=30, verbose_name='Class Time(Day of Week)')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='School Name')),
                ('address', models.TextField(blank=True, max_length=250, null=True, verbose_name='School Address')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(default='CIS101', help_text='Subject Code, e.g. CIS101', max_length=20, primary_key=True, serialize=False, verbose_name='Subject Code')),
                ('title', models.CharField(max_length=100, verbose_name='Subject Title')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Subject Description')),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.TimeField(verbose_name='Start Time')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Full Name')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Type Name')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Type Description')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubjectSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Schedule')),
                ('user_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.UserSubject')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.UserType', verbose_name='User Type'),
        ),
        migrations.AddField(
            model_name='subject',
            name='users',
            field=models.ManyToManyField(through='timetable.UserSubject', to='timetable.User'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Section Name')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Group', verbose_name='Group')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.School', verbose_name='School')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='hour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Time'),
        ),
    ]
