# Generated by Django 2.2.1 on 2019-08-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='somerandomprop',
            field=models.TextField(default='Sample Random Prom'),
        ),
    ]
