# Generated by Django 2.2.1 on 2019-08-20 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_subject_somerandomprop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='somerandomprop',
        ),
    ]
