# Generated by Django 2.2.1 on 2019-08-16 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_schedule_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Country')),
            ],
        ),
        migrations.AlterField(
            model_name='school',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Country'),
        ),
    ]
