# Generated by Django 2.2.1 on 2019-08-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_groupsubject'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hours_per_week',
            field=models.IntegerField(default=1, verbose_name='Hours per Week'),
        ),
    ]
