# Generated by Django 2.2.1 on 2019-08-16 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20190816_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time',
            old_name='start',
            new_name='hour',
        ),
        migrations.CreateModel(
            name='UserSubjectSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.Schedule')),
                ('user_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timetable.UserSubject')),
            ],
        ),
    ]
